# Generated by Django 4.2 on 2023-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Meta Title of object')),
                ('slug', models.CharField(blank=True, max_length=80, verbose_name='Meta Slug of object')),
            ],
        ),
    ]
