# Generated by Django 4.2 on 2023-07-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
